#!/bin/bash
echo `date` >  ping.txt
printf "%s" "ESPERANDO AL SERVIDOR ..."
while ! ping -c 1 -n -w 2 10.10.10.1 &>/dev/null
do
    printf "%c" "."
done
printf "\n%s\n"  "EL SERVIDOR ESTÁ online" >> ping.txt

curl -T /home/pi/ping.txt ftp://raspi:hrsp100namp@10.10.10.1/ping.txt &

