#!/bin/bash
echo `date` > gps.txt
printf "ESPERANDO AL GPS"
#ipgps=`gpspipe -r -n 15 | grep -n 'GNGGA' -m 1 | cut -d "," -f 7`

while [ `gpspipe -r -n 15 | grep -n 'GNGGA' -m 1 | cut -d , -f 7` -lt 1 ]
do
	printf "\n gps inactivo" >> gps.txt
#	ipgps=`gpspipe -r -n 15 | grep -n GNGGA -m 1 | cut -d , -f 7`
	curl -T /home/pi/gps.txt ftp://raspi:hrsp100namp@10.10.10.1/gps.txt &
	sleep 30
done

printf "\n gps activo\n" >> gps.txt

curl -T /home/pi/gps.txt ftp://raspi:hrsp100namp@10.10.10.1/gps.txt &
